Refactor `bitrise.yml`
bitrise-steplib/steps-ios-auto-provision pull request #149
Opened 2021-06-07 14:10 UTC by istvankovacs-bitrise

### Checklist

- [X] I've read and accepted the [Contribution Guidelines](https://github.com/bitrise-steplib/.github/blob/main/CONTRIBUTING.md)
- Requires _PATCH_ [version update](https://semver.org/)

### Changes
- E2E test cases moved from the root `bitrise.yml` to the `e2e/bitrise.yml`.
- Default workflows (`check` and `sample`) added to the root `bitrise.yml`.

2021-06-07 15:53 UTC, lpusok commented on bitrise.yml
> +  e2e_tests:
```suggestion
  e2e:
    steps:
    - git::https://github.com/bitrise-steplib/steps-check.git:
        inputs:
        - workflow: e2e
```

2021-06-07 15:55 UTC, lpusok commented on bitrise.yml
> +    - git::https://github.com/bitrise-steplib/bitrise-step-simple-git-clone.git@master:
```suggestion
    - git::https://github.com/bitrise-steplib/bitrise-step-simple-git-clone.git:
```

2021-06-07 15:56 UTC, lpusok commented on e2e/bitrise.yml
> +                if [ "$BITRISE_EXPORT_METHOD" != "$DISTRIBUTION_TYPE" ]; then exit 1; fi
```suggestion
                if [ "$BITRISE_EXPORT_METHOD" != "$DISTRIBUTION_TYPE" ]; then exit 1; fi

```

2021-06-07 15:56 UTC, lpusok commented on e2e/bitrise.yml
> +    - git::https://github.com/bitrise-steplib/bitrise-step-simple-git-clone.git@master:
```suggestion
    - git::https://github.com/bitrise-steplib/bitrise-step-simple-git-clone.git:
```

2021-06-07 16:02 UTC, lpusok reviewed
Pls check comments

2021-06-08 08:42 UTC, lpusok requested changes

2021-06-08 08:42 UTC, lpusok commented on bitrise.yml
> +    steps:
pls remove lines 39-70

2021-06-08 10:44 UTC, lpusok commented on e2e/bitrise.yml
> +      Test only wired in on Bitrise.io, since this workflow needs to run on new Xcode 11 stack,
"Test only wired in..." is no longer true. Do you want to add a check for the Xcode stack in this PR?
Testing with the new CI is not yet in scope is that right?

2021-06-08 11:06 UTC, istvankovacs-bitrise commented on e2e/bitrise.yml
> +      Test only wired in on Bitrise.io, since this workflow needs to run on new Xcode 11 stack,
Valid point! Previously there was a separate WF with the desired stack to launch this test, but this is obviously not an option for the Unified CI. Do you have something in mind on how to handle this?

2021-06-08 14:36 UTC, lpusok commented on e2e/bitrise.yml
> +      Test only wired in on Bitrise.io, since this workflow needs to run on new Xcode 11 stack,
This os OK as short term solution

2021-06-08 14:37 UTC, lpusok approved these changes

2021-06-15 11:01 UTC, mateherber approved these changes

2021-06-15 11:11 UTC, merged