Step 1316 fix disable device registration
bitrise-steplib/steps-ios-auto-provision pull request #157
Opened 2021-08-03 08:20 UTC by godrei

### Checklist

- [x] I've read and accepted the [Contribution Guidelines](https://github.com/bitrise-steplib/.github/blob/main/CONTRIBUTING.md)
- Requires _PATCH_ [version update](https://semver.org/)

### Context

In the case `register_test_devices` Step Input is disabled. DeviceClient.ensure_test_devices gets nil test_devices which makes the function failing:

```
Error:
undefined method `empty?' for nil:NilClass

Stacktrace (for debugging):
/private/var/folders/1g/5x0_q2sd6lx3phgrzb7zp4800000gp/T/bitrise100754332/step_src/lib/autoprovision/portal/device_client.rb:17:in `ensure_test_devices'
/var/folders/1g/5x0_q2sd6lx3phgrzb7zp4800000gp/T/bitrise100754332/step_src/step.rb:85:in `<main>'

```

### Changes

- Handle test_devices=nil in ensure_test_devices function.

### Investigation details

### Decisions

2021-08-03 14:43 UTC, lpusok submitted a review, later dismissed

2021-08-03 14:45 UTC, Bence1001 requested changes

2021-08-03 14:45 UTC, Bence1001 commented on lib/autoprovision/portal/device_client.rb
> +      unless test_devices.to_a.empty?
Shouldn't this be handled by the caller?

I think passing `nil` to `ensure_test_devices` doesn't make much sense (and therefore shouldn't be handled as "expected").

See my comment below! 👇

2021-08-03 14:45 UTC, Bence1001 commented on step.rb
>      test_devices = auth.test_devices if params.register_test_devices == 'yes'
Shouldn't we initialize `test_devices` as such to avoid `nil`?
```ruby
test_devices = params.register_test_devices == 'yes' ? auth.test_devices : []
```

2021-08-03 14:45 UTC, Bence1001 commented on step.rb
> +  if distribution_type_requires_device_list
Does this fix a separate bug?

2021-08-03 14:46 UTC, godrei commented on step.rb
> +  if distribution_type_requires_device_list
yes

2021-08-04 07:45 UTC, godrei commented on lib/autoprovision/portal/device_client.rb
> +      unless test_devices.to_a.empty?
makes sense, fixed in https://github.com/bitrise-steplib/steps-ios-auto-provision/pull/157/commits/0333d12ec4581d97f278fe70b09ff2170e5daed7

2021-08-04 07:46 UTC, godrei commented on step.rb
>      test_devices = auth.test_devices if params.register_test_devices == 'yes'
makes sense, fixed in https://github.com/bitrise-steplib/steps-ios-auto-provision/pull/157/commits/0333d12ec4581d97f278fe70b09ff2170e5daed7

2021-08-04 07:51 UTC, Bence1001 commented on step.rb
> +  if distribution_type_requires_device_list
Gotcha, thanks @godrei for clarifying! 🙏

2021-08-04 07:51 UTC, Bence1001 approved these changes
LGTM! 👍

2021-08-04 08:18 UTC, merged